export interface TextRules {
  level: 'minimal' | 'medium' | 'full';
  includeOffer: boolean;
  includeCta: boolean;
  style: 'elegant' | 'bold' | 'conversational' | 'provocative' | 'playful' | 'scientific' | 'sensual' | 'mysterious';
}

export interface ArchetypeDefinition {
  id: string;
  label: string;
  icon: string;
  audience: string;
  categories: string;
  formula: string;
  risk: string;
  tags: string[];
  platforms: string[];
  textRules: TextRules;
}

export const ARCHETYPES: ArchetypeDefinition[] = [
  { id: "mem", label: "Мем", icon: "😂", audience: "18–35, активные пользователи соцсетей", categories: "Одежда, гаджеты, FMCG", formula: "Крупный объект + короткий острый текст в стиле мема", risk: "Быстро устаревает", tags: ["Ирония", "Узнавание", "Виральность"], platforms: ["Instagram", "TikTok", "VK"], textRules: { level: 'medium', includeOffer: false, includeCta: true, style: 'bold' } },
  { id: "trend", label: "Трендовый", icon: "🔥", audience: "16–35, TikTok/YouTube", categories: "Одежда, электроника, косметика", formula: "Атмосфера актуального тренда без прямого копирования", risk: "Тренд может умереть раньше запуска", tags: ["Хайп", "Актуальность", "Волна"], platforms: ["TikTok", "Instagram", "YouTube"], textRules: { level: 'medium', includeOffer: false, includeCta: true, style: 'bold' } },
  { id: "aesthetic", label: "Эстетический", icon: "✦", audience: "20–45, женщины, ценители дизайна", categories: "Украшения, косметика, декор, мебель", formula: "Чистая композиция + выверенный цвет + минимум текста", risk: "Может выглядеть холодно и не продавать", tags: ["Вкус", "Стиль", "Воздух"], platforms: ["Instagram", "Pinterest"], textRules: { level: 'minimal', includeOffer: false, includeCta: false, style: 'elegant' } },
  { id: "cringe", label: "Кринжовый", icon: "🤪", audience: "18–35, TikTok, любители иронии", categories: "Дешёвые товары, подарки, мерч, FMCG", formula: "Осознанный колхозный баннер — контраст с конкурентами", risk: "Может навредить имиджу если ЦА не поймёт иронию", tags: ["Трэш", "Ирония", "Контраст"], platforms: ["TikTok", "VK"], textRules: { level: 'medium', includeOffer: false, includeCta: true, style: 'provocative' } },
  { id: "wow", label: "WOW-архетип", icon: "🎬", audience: "20–45, любящие дорогой стиль", categories: "Авто, электроника, спорттовары, премиум", formula: "Продукт — герой кадра: драматический свет, крупные планы", risk: "Дорого в производстве", tags: ["Кино", "Крутизна", "Визуал"], platforms: ["YouTube", "Instagram", "Facebook"], textRules: { level: 'medium', includeOffer: false, includeCta: true, style: 'bold' } },
  { id: "acid", label: "Кислотный", icon: "⚡", audience: "16–35, Gen Z, геймеры", categories: "Стритвир, кроссовки, игровые девайсы", formula: "Неоновые цвета + глич-эффекты + киберпанк-вайб", risk: "Не работает для взрослой ЦА", tags: ["Неон", "Энергия", "Gen Z"], platforms: ["TikTok", "Instagram"], textRules: { level: 'full', includeOffer: true, includeCta: true, style: 'provocative' } },
  { id: "zhiza", label: "Жиза", icon: "🏠", audience: "25–55, семьи, родители", categories: "Товары для дома, кухни, ремонта, дачи", formula: "Продукт в узнаваемых бытовых ситуациях — это про меня", risk: "Может выглядеть скучно", tags: ["Узнавание", "Быт", "Реализм"], platforms: ["VK", "Facebook", "Instagram"], textRules: { level: 'medium', includeOffer: false, includeCta: true, style: 'conversational' } },
  { id: "premium", label: "Премиум", icon: "💎", audience: "25–55, доход средний+", categories: "Ювелирка, часы, элитная техника, интерьер", formula: "Тёмный фон + благородные материалы + минималистичный текст", risk: "Если продукт не соответствует визуалу — недоверие", tags: ["Статус", "Класс", "Роскошь"], platforms: ["Instagram", "Facebook"], textRules: { level: 'minimal', includeOffer: false, includeCta: false, style: 'elegant' } },
  { id: "nostalgia", label: "Ностальгический", icon: "📼", audience: "25–45, помнящие 90-е/2000-е", categories: "Сладости, ретро-одежда, игрушки, подарки", formula: "VHS-эффект, ретро-шрифты, визуальные коды прошлого", risk: "Не работает для молодой ЦА", tags: ["90-е", "Память", "Тепло"], platforms: ["VK", "Facebook", "Instagram"], textRules: { level: 'medium', includeOffer: false, includeCta: true, style: 'conversational' } },
  { id: "story", label: "Сюжетный", icon: "📖", audience: "Широкая ЦА, рациональные покупатели", categories: "Бытовая техника, уходовые средства, спорт", formula: "До/после, проблема → решение в одном кадре", risk: "Требует сильного копирайта", tags: ["До/после", "История", "Результат"], platforms: ["Instagram", "Facebook", "YouTube"], textRules: { level: 'full', includeOffer: true, includeCta: true, style: 'conversational' } },
  { id: "social_proof", label: "Соцдоказательство", icon: "⭐", audience: "25–55, осторожные покупатели", categories: "Косметика, техника, мебель, дорогие товары", formula: "Отзывы + рейтинги + UGC-фото на баннере", risk: "Отзывы должны выглядеть подлинно", tags: ["Доверие", "Отзывы", "Рейтинг"], platforms: ["Instagram", "Facebook", "Google Display"], textRules: { level: 'full', includeOffer: true, includeCta: true, style: 'bold' } },
  { id: "shock", label: "Шок/провокация", icon: "💥", audience: "18–40, открытые к смелому маркетингу", categories: "Спорт, фитнес, гаджеты, стрит-бренды", formula: "Неожиданные образы + парадоксы + провокационные формулировки", risk: "Легко перейти черту и получить бан", tags: ["Взрыв", "Вызов", "Внимание"], platforms: ["TikTok", "Instagram"], textRules: { level: 'full', includeOffer: true, includeCta: true, style: 'provocative' } },
  { id: "science", label: "Научный", icon: "🔬", audience: "25–55, инженеры, B2B", categories: "Инструменты, техника, B2B-решения, медицина", formula: "Схемы + графики + цифры + лабораторный стиль", risk: "Скучный визуал без продающего текста", tags: ["Логика", "Факты", "Данные"], platforms: ["Google Display", "Facebook", "YouTube"], textRules: { level: 'full', includeOffer: true, includeCta: true, style: 'scientific' } },
  { id: "asmr", label: "ASMR / Мягкий", icon: "🧸", audience: "20–55, женщины, семьи", categories: "Текстиль, свечи, SPA, уход", formula: "Мягкий свет + крупные планы текстур + хочется потрогать", risk: "Слишком мягкий визуал может не стимулировать клик", tags: ["Комфорт", "Текстура", "Тепло"], platforms: ["Instagram", "Pinterest"], textRules: { level: 'minimal', includeOffer: false, includeCta: false, style: 'elegant' } },
  { id: "gamification", label: "Геймификация", icon: "🎮", audience: "16–40, геймеры, любители интерактивов", categories: "Игры, гаджеты, подписки, обучение", formula: "Баннер в логике игры: выбор, кнопки, квест", risk: "Может отвлечь от самого продукта", tags: ["Игра", "Вовлечение", "Интерактив"], platforms: ["TikTok", "YouTube", "Instagram"], textRules: { level: 'full', includeOffer: true, includeCta: true, style: 'playful' } },
  { id: "surreal", label: "AI-Сюрреализм", icon: "🌀", audience: "18–40, любители арта и нейросетей", categories: "Одежда, декор, хобби, подарки", formula: "Левитация + необычная физика + магические эффекты", risk: "Может выглядеть странно для консервативной ЦА", tags: ["Фантазия", "Арт", "Неожиданность"], platforms: ["Instagram", "TikTok", "Pinterest"], textRules: { level: 'minimal', includeOffer: false, includeCta: false, style: 'provocative' } },
  { id: "cultural", label: "Культурный код", icon: "🌍", audience: "Локальные рынки, диаспоры", categories: "Продукты питания, сувениры, локальные бренды", formula: "Локальные символы + традиции + язык для своих", risk: "Не масштабируется за пределы региона", tags: ["Локальность", "Свои", "Традиции"], platforms: ["VK", "Instagram"], textRules: { level: 'medium', includeOffer: false, includeCta: true, style: 'conversational' } },
  { id: "hyperbole", label: "Гиперболизация", icon: "🚀", audience: "18–45, любители юмора", categories: "Техника, спорт, energy-товары", formula: "Утрируем свойства до смешного/эпичного", risk: "Может не донести реальную пользу", tags: ["Эпик", "Юмор", "Преувеличение"], platforms: ["TikTok", "YouTube", "Instagram"], textRules: { level: 'full', includeOffer: true, includeCta: true, style: 'bold' } },
  { id: "cinematic", label: "Синематический", icon: "🎥", audience: "18–45, любители кино", categories: "Авто, техника, гаджеты", formula: "Кадр из жанра кино: боевик, sci-fi, драма", risk: "Без высокого продакшна выглядит дёшево", tags: ["Кино", "Жанр", "Драма"], platforms: ["YouTube", "Instagram", "Facebook"], textRules: { level: 'minimal', includeOffer: false, includeCta: false, style: 'elegant' } },
  { id: "cat", label: "Котоархетип", icon: "🐱", audience: "18–40, женщины, владельцы животных", categories: "Практически любые категории — чит-код!", formula: "Продукт + кот + минимум текста + мягкое освещение", risk: "Внимание может уйти на кота", tags: ["Милота", "Доверие", "Вирус"], platforms: ["Instagram", "VK", "TikTok"], textRules: { level: 'minimal', includeOffer: false, includeCta: false, style: 'playful' } },
  { id: "eco", label: "Экологичный", icon: "🌿", audience: "20–50, сознательные покупатели", categories: "Бытовая химия, еда, косметика", formula: "Продукт + природа/зелёный фон + иконки экофич", risk: "Гринвошинг если продукт не реально экологичный", tags: ["Планета", "Осознанность", "Зелёный"], platforms: ["Instagram", "Facebook", "Pinterest"], textRules: { level: 'medium', includeOffer: false, includeCta: true, style: 'elegant' } },
  { id: "cute", label: "Милота", icon: "🩷", audience: "18–35, женщины, молодые родители", categories: "Игрушки, аксессуары, детские товары", formula: "Мини-продукт + мягкие текстуры + пастельные цвета", risk: "Не работает для статусных продуктов", tags: ["Уют", "Нежность", "Умиление"], platforms: ["Instagram", "Pinterest", "VK"], textRules: { level: 'minimal', includeOffer: false, includeCta: false, style: 'playful' } },
  { id: "pov", label: "POV", icon: "👁", audience: "16–40, Gen Z, геймеры, DIY", categories: "Гаджеты, спорт, инструменты", formula: "Камера = глаза пользователя, руки + активное действие", risk: "Плохо снятый POV выглядит дёшево", tags: ["Присутствие", "Действие", "Реализм"], platforms: ["TikTok", "YouTube", "Instagram"], textRules: { level: 'medium', includeOffer: false, includeCta: true, style: 'conversational' } },
  { id: "celebrity", label: "Ассоциация с персоной", icon: "🧠", audience: "18–45, мыслящие через образы", categories: "Обучение, умные продукты, детские товары", formula: "Как у Эйнштейна/Илона — перенос смысла без прямого использования", risk: "Юридические вопросы при неаккуратном использовании", tags: ["Перенос смысла", "Авторитет", "Вау"], platforms: ["Instagram", "Facebook", "YouTube"], textRules: { level: 'full', includeOffer: true, includeCta: true, style: 'conversational' } },
  { id: "badgood", label: "Чем хуже тем лучше", icon: "📉", audience: "18–35, Gen Z, уставшие от рекламы", categories: "Дешёвые товары, FMCG, недорогие гаджеты", formula: "Осознанно ломаем качество подачи — контраст с конкурентами", risk: "Сложно отличить от реально плохой рекламы", tags: ["Антиреклама", "Контраст", "Честность"], platforms: ["TikTok", "VK"], textRules: { level: 'full', includeOffer: true, includeCta: true, style: 'provocative' } },
  { id: "seduction", label: "Соблазн", icon: "🔥", audience: "18–45, ценители эстетики и чувственности", categories: "Парфюмерия, бельё, косметика, фитнес, spa, dating, вино, шоколад, ювелирка, fashion", formula: "Чувственность + притяжение + элегантная провокация. Метафоры тела: прикосновение, тепло кожи, изгибы, шёлк", risk: "Легко перейти в пошлость — нужна элегантность", tags: ["Желание", "Притяжение", "Удовольствие", "Соблазн", "Страсть"], platforms: ["Instagram", "TikTok", "YouTube"], textRules: { level: 'medium', includeOffer: false, includeCta: true, style: 'sensual' } },
  { id: "black-box", label: "Чёрный ящик", icon: "📦", audience: "20–45, IT-аудитория, крипто, закрытые сообщества", categories: "IT-продукты, SaaS, крипто, VPN, кибербезопасность, закрытые клубы, pre-launch, инфопродукты", formula: "Засекреченная технология + доступ только для избранных. Язык спецслужб: допуск, рассекречено, утечка", risk: "Может выглядеть как спам или скам если переборщить", tags: ["Секретно", "Доступ", "Допуск", "Избранные", "Эксклюзив", "Рассекречено"], platforms: ["Telegram", "Instagram", "VK"], textRules: { level: 'full', includeOffer: true, includeCta: true, style: 'mysterious' } },
];

/** Список названий для системного промта AI */
export const ARCHETYPE_NAMES_LIST = ARCHETYPES.map((a) => a.id).join(', ');
